name: Release bot

run-name: ${{ github.ref_name }}

on:
  push:
    tags:
      - v*

jobs:
  delivery:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.PRODUCTION_HOST }}
          username: ${{ vars.PRODUCTION_USER }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          script: |
            cd /home/devops/watermark_bot
            docker stop watermark-bot
            docker remove watermark-bot
            printf '%s\n' '${{ secrets.DOCKER_PASSWORD }}' | docker login -u ${{ vars.DOCKER_USER }} --password-stdin
            docker pull ${{ vars.DOCKER_REGISTRY }}/watermark-bot:latest
            docker run --env-file ./.env.production --name watermark-bot -d  ${{ vars.DOCKER_REGISTRY }}/watermark-bot 
            docker logout ${{ vars.DOCKER_REGISTRY }}